# -*- mode: python ; coding: utf-8 -*-
import os

block_cipher = None
spec_root = os.path.abspath(SPECPATH)

a = Analysis(
    ['main.py'],
    pathex=[spec_root],
    binaries=[],
    datas=[
        ('settings.ini', '.'),
        ('jasco.ico', '.'),
        ('userscripts', 'userscripts'),
    ],
    hiddenimports=[
        # Local modules
        'ui',
        'tray',
        'tab_home',
        'tab_settings',
        'tab_tools',
        'state',
        'settings',
        'config',
        'constants',
        'chrome',
        'launcher',
        'bookmarks',
        'utils',
        'tools_decant',
        'tools_slotstax',
        'userscript_updater',
        'userscript_injector',
        'retry_utils',
        # External dependencies
        'selenium',
        'selenium.webdriver',
        'selenium.webdriver.chrome.service',
        'selenium.webdriver.common.by',
        'selenium.webdriver.support.ui',
        'selenium.webdriver.support.expected_conditions',
        'ldap3',
        'pystray',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'pygetwindow',
        'pywin32',
        'win32gui',
        'win32api',
        'win32event',
        'winerror',
        'requests',
        'tkinter',
        'tkinter.ttk',
        'tkinter.font',
        'tkinter.messagebox',
        'webdriver_manager',
        'webdriver_manager.chrome',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='BrowserControl',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='jasco.ico',
)
